---
test:
  build: "."
  dockerfile: Dockerfile.ci
  working_dir: "/app"
  volumes:
  - "./vendor/bundle:/usr/local/bundle"
  - "$CIRCLE_TEST_REPORTS/rspec:$HOME/.rspec_reports"
  environment:
    RAILS_ENV: test
    POSTGRESQL_USER: postgres
    POSTGRESQL_HOST: postgresql
    POSTGRESQL_PORT: '5432'
  links:
  - postgre
postgresql:
  image: postgres:9.6.1
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ''
