#!/bin/sh

# Setup heroku application remotes
if heroku auth:whoami &> /dev/null; then
  if heroku apps:info --app pl-ptexpress-staging &> /dev/null; then
    git remote add staging git@heroku.com:pl-ptexpress-staging.git || true
    git config heroku.remote staging
    echo 'You are a collaborator on the "pl-ptexpress-staging" Heroku app'
  else
    echo 'Ask for access to the "pl-ptexpress-staging" Heroku app'
  fi

  if heroku apps:info --app pl-ptexpress-production &> /dev/null; then
    git remote add production git@heroku.com:pl-ptexpress-production.git || true
    echo 'You are a collaborator on the "pl-ptexpress-production" Heroku app'
  else
    echo 'Ask for access to the "pl-ptexpress-production" Heroku app'
  fi
else
  echo 'You need to login to heroku. Run "heroku login"'
fi
